# Server Configuration
bind_address = "0.0.0.0:25565"
motd = "Minecraft High Performance Redstone Server"
chat_format = "<{username}> {message}"
max_players = 99999
view_distance = 8
whitelist = false
schemati = false
block_in_hitbox = true
auto_redpiler = false

# Velocity Configuration
[velocity]
enabled = true
# This is the secret contained within `forwarding-secret-file` from your velocity config,
# NOT the path to the file.
secret = "${VELOCITY_SECRET}"

# LuckPerms Configuration
[luckperms]
# Define the address for the database.
host = "postgres:5432"
# The name of the database the LuckPerms data is in.
db_name = "${POSTGRES_DB}"
# Credentials for the database.
username = "${POSTGRES_USER}"
password = "${POSTGRES_PASSWORD}"
# The name of the server, used for server specific permissions.
# See: https://luckperms.net/wiki/Context
server_context = "global"